name: Release

on:
  push:
    branches:
      - main
      - develop

jobs:
  release:
    permissions:
      contents: write
      issues: write
      pull-requests: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.x
          cache: 'npm'

      - name: Install dependencies
        run: npm install
      
      - name: Set branch name environment variable
        run: echo "BRANCH_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          BRANCH_NAME: ${{ env.BRANCH_NAME }}
        run: npx semantic-release
